import Head from "next/head";
import styles from "../styles/Home.module.css";
import Whitelist from "../components/whitelists/Whitelist";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>C& Whitelist Dashboard</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Whitelist />
    </div>
  );
}
